### DISCUSSION TITLE
Usage with gitlab.ci and multiple shard ?

### DISCUSSION THREAD

**Discussion by samixchoumi** [ryanrosello-og/playwright-slack-report#124] [Q&A] [answered]
Hello, does anyone have a sample project that works well with parallelisation using gitlab-ci file (so multiple shard), a `SLACK_WEBHOOK_URL` and this plugin for slack reporting ?

I tried multiple solution by looking at the documentation but it's still doing some weird behavior like sending all gitlab runner test execution instead of waiting for the merge to be done.

Actually i've something like : 

```
.merge_reports:
  stage: merge_reports
  image: mcr.microsoft.com/playwright:v1.43.0-jammy
  script:
    - echo "Merging test reports..."
    - mkdir -p all-blob-reports
    - cp -r blob-report/* all-blob-reports/
    - npx playwright merge-reports --reporter json ./all-blob-reports > merged_tests_results.json
  artifacts:
    paths:
      - all-blob-reports/
      - merged_tests_results.json
    expire_in: 1 week

.notify_slack:
  stage: notify
  dependencies:
    - merge_reports
  script:
    - echo "Sending Slack notification..."
    - npm install playwright-slack-report
    - npx playwright-slack-report --json-results="./merged_tests_results.json"
```

And my test steps just run the script : `"test": "npx bddgen && npx playwright test --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL",`

I've my playwright config looking like that : 
```
reporter: [
    [
      "./node_modules/playwright-slack-report/dist/src/SlackReporter.js",
      {
        sendResults: "always",
        slackWebHookUrl: process.env.SLACK_WEBHOOK_URL
      },
    ],
    cucumberReporter('html', { outputFile: 'cucumber-report/report.html' }),
    cucumberReporter('json', { outputFile: 'cucumber-report/report.json' }),
    ['blob'],
  ],

```
Do you have any idea on what is wrong here ? Or at least a working sample project with Gitlab and parallelization so I could take a look ?
